version: "3"

services:
  apimaster:
    container_name: exampleapp
    restart: always
    build: .
    ports:
      - "5000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: proyectouno
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
    volumes:
      - persistencia:/data/db
volumes:
  persistencia:
